### ISSUE TITLE
[Bug] Cannot access website

### ISSUE THREAD

**Issue by rmredder** [RedwanIbneSerajKhan/Food-Web#114]
The website seems to be down, I tried to access the website from the links in your readme but was shown the following screen. I attempted at two different times today as well as on different computers, so I don't believe it is my machine.

![image](https://user-images.githubusercontent.com/31999343/39787231-563e9d4e-52f2-11e8-9e63-7a551c10b168.png)

**Comment by RedwanIbneSerajKhan** [comment]
The server sometimes has these issues where it is unable to get redirected to the site. Thank you for informing us. Can you try again? We have checked it and it is working. We apologize that you had to go through this trouble.

**Comment by RedwanIbneSerajKhan** [comment]
Thank you for being patient with us. We truly appreciate it.
