### ISSUE TITLE
[Critical Bug] Site down

### ISSUE THREAD

**Issue by nlagrassa** [RedwanIbneSerajKhan/Food-Web#115]
I am unable to access your site. When I click your URL (the same provided in your README and official release video), I get the following page:
![image](https://user-images.githubusercontent.com/13890831/39933841-0ce92d04-5512-11e8-9ac7-79e76b66e9d7.png)

OS: macOS High Sierra Version 10.13.4
Browser: Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by ankitner** [comment]
Hi,

There was some issue with the server. Can you try again? We have checked it and it is working. We apologize for this.
