### ISSUE TITLE
Make feature that a user can upload a image from his/her PC

### ISSUE THREAD

**Issue by gauravav** [RedwanIbneSerajKhan/Food-Web#54]
We currently have a feature that can take an image URL or address and that shows up on the main page along with the food described. We also want a new feature where a user can upload a file image from his/her personal PC.
![file upload issue](https://user-images.githubusercontent.com/36088481/38048610-dcdd3fd8-3293-11e8-9fc4-e3d53d1f1005.JPG)

**Comment by RedwanIbneSerajKhan** [comment]
Done.
