### ISSUE TITLE
Add an option to Sign up with Facebook.

### ISSUE THREAD

**Issue by ankitner** [RedwanIbneSerajKhan/Food-Web#55]
**Task:** The present Sign up/register form asks to create an account with a username and password. The task is to provide an option to Sign up with Facebook and obtain the username and password from facebook.

![capture](https://user-images.githubusercontent.com/33841935/38049737-f7a664fe-3296-11e8-943f-8d9a7312de5b.JPG)

**Upon the completion of task:**

User can now create an account by providing a username and password or with the an option of facebook Sign Up and also login with facebook.

![signup](https://user-images.githubusercontent.com/33841935/38049528-7710a296-3296-11e8-8fd4-063815a90753.png)

**Comment by i-r-a** [comment]
In order to do this task, am I using landing.ejs, and login.ejs? Also, how do I test this locally?

**Comment by ankitner** [comment]
Hi,

You can look at this tutorial(video) on how to setup node.js and mongodb .

Here is the link : https://www.youtube.com/watch?v=yWSmy8jVz1Q

Hope this helps.

**Comment by RedwanIbneSerajKhan** [comment]
Done.
