### ISSUE TITLE
Restaurant info not displayed in search results [bug]

### ISSUE THREAD

**Issue by btackett3** [RedwanIbneSerajKhan/Food-Web#59]
Problem:  

When getting search results, you are given an image and the name of the dish.  You get a button to get more info, but it would be helpful to have some information about the dish in the results page.  For example, the two BBQ Tofu dishes appear identical, even though they come from different restaurants and have different ratings.

Category:

Minor Bug.  The app is still usable, but fixing this would be very helpful.

How I Found Bug:

Create two dish entries with the same name (BBQ Tofu Sandwich (Vegan)).  Try searching for them.  Notice that they look the same.  

Using:

Windows 10, Google Chrome, Laptop

Proposed Solution:  

Show restaurant name and rating in search thumbnails.

**Comment by RedwanIbneSerajKhan** [comment]
We are working on implementing this feature. Thank you for pointing it out.
