### ISSUE TITLE
[Minor Bug] The entry boxes as well as the images of each food item are not uniformed

### ISSUE THREAD

**Issue by shallyguo** [RedwanIbneSerajKhan/Food-Web#60]
As said in the description, each dish entries and food image pictures are not uniformly displayed on the web page. As shown in the image below, some of the entries take up more space on the web page than others. 

The environment in where I am loading the website is Google Chrome. 

![screen shot 2018-03-28 at 11 50 31 pm](https://user-images.githubusercontent.com/31744330/38069163-f1e48266-32e2-11e8-96bc-178ed375bedf.png)

**Comment by gauravav** [comment]
We are working on it.

**Comment by RedwanIbneSerajKhan** [comment]
Have a look at https://unsplash.com/ . See how the different size of images adds to the beauty of the site? We are choosing to move with this design of our project rather than changing it. Thanks for your recommendation.
