### ISSUE TITLE
[Critical Bug] Website does not show with provided link

### ISSUE THREAD

**Issue by apkillion** [RedwanIbneSerajKhan/Food-Web#66]
After following the instructions in the README and following the link 
( https://webdevbootcamp-ankitner.c9users.io/dishes)
the host web address led to to a page pictured below saying that the workspace didn't exist.  I attempted reaching the site several times at different times on different days just in case a server was down or being worked on.

![website failure](https://user-images.githubusercontent.com/11025435/38636949-bd79da98-3d97-11e8-9110-d74093ed6fb5.png)

**Comment by RedwanIbneSerajKhan** [comment]
Sorry that you have had this experience.  We were working on a few updates in our site(as the grading of the alpha release was over) and for that reason we had closed down our server when we were working. That might have been the time you tried to get in. This is not a bug. You can try it again after the Beta Release of our website today. I hope it will work just fine.
