### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by z28980361** [RedwanIbneSerajKhan/Food-Web#73]
I would recommended you guys to add validation on fields like restaurant name and name of the dish when adding a new dish. The only validation it has when adding a new dish is the location while the rest could be empty. This will allow users to create useless data on the website. ( Someone already did, and I was one of them ;)

**Comment by RedwanIbneSerajKhan** [comment]
We will be working to improve this feature to avoid spams. Thanks for your review.

**Comment by RedwanIbneSerajKhan** [comment]
Done.
