### ISSUE TITLE
Minor Bug Map is zoomed in too far

### ISSUE THREAD

**Issue by alphathunderwave** [RedwanIbneSerajKhan/Food-Web#74]
![screenshot from 2018-04-17 12-54-00](https://user-images.githubusercontent.com/12668396/38884731-759ac4e8-423e-11e8-935c-abde84f7c88c.png)
the map in the food page is a bit small to understand the context of where the restaurant is located

**Comment by RedwanIbneSerajKhan** [comment]
Thank you for your review. If you want the map to zoom out just press on the '-' symbol at the lower right corner of google map. Click on the the man shape there to get a street view. These are all google map features and not bugs. Thanks for your time.
