### ISSUE TITLE
Feature Request/Bug

### ISSUE THREAD

**Issue by YongJi97** [RedwanIbneSerajKhan/Food-Web#75]
Make the images of dishes be more organized and aligned with each other.

**Comment by RedwanIbneSerajKhan** [comment]
We are not planning on making images aligned with each other. Have a look at https://unsplash.com/ . See how the different sizes of the images add to the dynamic nature of the site? This is not a bug but we might consider reshaping up a few features depending upon public opinions. But for now, we would be closing this issue as this is not a bug.
