### ISSUE TITLE
Alpha Testing- [Feature Request] Change username requirements to be less strict

### ISSUE THREAD

**Issue by mattCarapella** [RedwanIbneSerajKhan/Food-Web#81]
I use the same username for a lot of sites and having to be confined to only 10 letters and no numbers is too restrictive in my opinion. Increase the number of characters you can use to 20 or something and allow numbers. If you ever need to scale your site in the future, you're going to run into the issue of running out of unique usernames that aren't just random combinations of (maximum 10) letters fairly quickly I would assume.

**Comment by RedwanIbneSerajKhan** [comment]
The reason we did that is because it reduced the chances of getting spammed. But what you mentioned is also reasonable. We will try to find a solution that will prevent spamming and as well as take into consideration what you just mentioned.

**Comment by ankitner** [comment]
Solved. Although we preferred not to use numbers in username.
