### ISSUE TITLE
[Minor Bug] Uninformative rejection of username

### ISSUE THREAD

**Issue by cb56** [RedwanIbneSerajKhan/Food-Web#86]
This is for the collaboration phase. When I tried to make my username cb56_, it was rejected because "username must be between five and ten characters and cannot have spaces," technically, i met these requirements, so you could make a more specific rejection message

**Comment by RedwanIbneSerajKhan** [comment]
We are looking into this. Thanks for your feedback.

**Comment by ankitner** [comment]
This issued is now resolved.
