### ISSUE TITLE
[Trivial Bug] homepage takes a long time to load 

### ISSUE THREAD

**Issue by shallyguo** [RedwanIbneSerajKhan/Food-Web#89]
The homepage takes awhile to load. I think it might have to do with the image size for the homepage.

**Comment by RedwanIbneSerajKhan** [comment]
The homepage seems to be working fine. Are you talking about the first image that comes up after a black screen? This one is a slide show and we have implemented it to show up after a certain amount of time in regular intervals. We would not consider this as a bug.
