### ISSUE TITLE
[Trivial Bug] No response when search query doesn't match

### ISSUE THREAD

**Issue by ianleshan** [RedwanIbneSerajKhan/Food-Web#90]
When I type in a search term that does not exist, it just shows a blank screen. Maybe you should add some feedback to show that nothing came up so that people don't think that the site is unresponsive.

**Comment by RedwanIbneSerajKhan** [comment]
We would not identify this as a bug rather we would like to consider your suggestion as a feature request. Thanks for your feedback.
